dist: xenial

language: minimal

git:
  depth: 1

branches:
  only:
    - esr68

env:
  global:
    - TOOLTOOL_DIR=$TRAVIS_BUILD_DIR/tools
    - SHELL=/bin/bash
    - REVOLTER_FIREFOX_VERSION=v68.1.$TRAVIS_BUILD_NUMBER
    - CC=clang-9
    - CXX=clang++-9

matrix:
  include:
    - name: "build for Linux"
    - name: "build for Windows"
      env:
        - BUILD_FOR_WINDOWS=true
      before_install:
      # download tools
        - mkdir -p $TOOLTOOL_DIR
        - cd $TOOLTOOL_DIR && pwd
        - wget -nv https://taskcluster-artifacts.net/E6GMKuBBTyi0SllWEAtxwg/0/public/build/clangmingw.tar.xz  # https://index.taskcluster.net/v1/task/gecko.cache.level-3.toolchains.v3.linux64-clang-8-mingw-x64.latest/artifacts/public/build/clangmingw.tar.xz
        - wget -nv https://taskcluster-artifacts.net/X2KEt8RQTZGpxxCx__ksXQ/0/public/build/rustc.tar.xz       # https://index.taskcluster.net/v1/task/gecko.cache.level-3.toolchains.v3.mingw32-rust-1.36.latest/artifacts/public/build/rustc.tar.xz
        - wget -nv https://taskcluster-artifacts.net/faq0ZDr8R3Ws89rRTVzjIg/0/public/build/cbindgen.tar.xz    # https://index.taskcluster.net/v1/task/gecko.cache.level-3.toolchains.v3.linux64-cbindgen.latest/artifacts/public/build/cbindgen.tar.xz
        - wget -nv https://taskcluster-artifacts.net/beAXMRJZT1a7zg6MbA-y-w/0/public/build/nsis.tar.xz        # https://index.taskcluster.net/v1/task/gecko.cache.level-3.toolchains.v3.linux64-mingw32-nsis.latest/artifacts/public/build/nsis.tar.xz
        - wget -nv https://taskcluster-artifacts.net/Ns7ruxQ9Sjquyyv1J3zpCA/0/public/build/fxc2.tar.xz        # https://index.taskcluster.net/v1/task/gecko.cache.level-3.toolchains.v2.linux64-mingw-fxc2-x86.latest/artifacts/public/build/fxc2.tar.xz
        - ls *.tar.xz | xargs -n1 tar -xJf
        - ls
        - cd -
      # decompress nsis
        - sudo mkdir -p /builds/worker/workspace/build/src/
        - cd /builds/worker/workspace/build/src/
        - sudo cp $TOOLTOOL_DIR/nsis.tar.xz .
        - sudo tar -xJf nsis.tar.xz
        - cd -
      install:
      # install wine
        - sudo dpkg --add-architecture i386
        - curl https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add
        - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
        - sudo add-apt-repository ppa:wine/wine-builds -y 
        - sudo apt-get update
        - sudo apt-get install -y wine-stable-amd64 wine-stable winehq-stable
        - wine --version

before_script:
  - timing () { while true; do date -u -Is; sleep 30; done }
  - timing &
  - echo "building $REVOLTER_FIREFOX_VERSION"
# mozconfig
  - echo -e "ac_add_options MOZ_PGO=1\nac_add_options --disable-av1\n" > mozconfig
# make sh file executable
  - chmod +x ./revolter-firefox-nss-build.sh
# mozconfig for windows build
  - if [[ $BUILD_FOR_WINDOWS = true ]]; then
      cat mozconfig-win >> mozconfig; 
    fi
  - cat mozconfig
# install lastest llvm
  - sudo apt-get remove -y llvm* clang* llvm clang
  # - sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main"
  - sudo apt-get update
  - sudo apt-get install -y clang-9 llvm-9-dev
# mach bootstrap
  - sudo apt-get install -y autoconf2.13 build-essential nodejs python-dev python-pip python-setuptools unzip uuid zip
  - sudo ./mach bootstrap --application-choice=browser --no-interactive

script:
# build
  - sudo chown root:root ~/  # solve `wine: '/home/travis' is not owned by you, refusing to create a configuration directory there`
  - sudo ./revolter-firefox-nss-build.sh
  - sudo chown -R travis:travis ~/

after_success:
  - cd $TRAVIS_BUILD_DIR
# check artifact
  - ls -al
  - ls dist/* -al
  - ls dist/**/*.@(dll|so)

before_deploy:
# tag this commit
  - git config --local user.name "$GITHUB_TAG_USERNAME"
  - git config --local user.email "$GITHUB_TAG_EMAIL"
  - git tag $REVOLTER_FIREFOX_VERSION

deploy:
  provider: releases
  edge: true
  tag_name: $REVOLTER_FIREFOX_VERSION
  target_commitish: $TRAVIS_COMMIT
  name: $REVOLTER_FIREFOX_VERSION
  release_notes: "&nbsp;"
  file:
    - ./dist/**/*.dll
    - ./dist/**/*.so
  file_glob: true
  on:
    all_branches: true

